version: "3.8"

services:
    frontend:
        depends_on:
            - backend
        build: ./frontend
        ports:
            - 3000:3000

    backend:
        depends_on:
            - db
        build: ./backend
        ports:
            - 8000:8000
        environment:
            DB_URL: mongodb://db/task-e2e
        command: ./docker-entrypoint.sh

    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            - task-e2e:/data/db

volumes:
    task-e2e:
